### PR TITLE
update hdk to v0.0.39-alpha4, and use Harris Braun sim2h switchboard

### PR DESCRIPTION
**Pull request by Connoropolous**
yay, no breaking changes to the code

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@Connoropolous what changed in the hdk in these versions? i didn't think we had any hdk updates recently :thinking:

**Comment by Connoropolous** [comment]
I wouldn't know we were just doing user testing and thought issues could arise if we mixed versions of binaries verse hdks

**Comment by thedavidmeister** [comment]
@Connoropolous oh yeah that makes sense, it's kinda annoying that hdk has such noisy versions for binary building

**Comment by Connoropolous** [comment]
Now I'd change this to  v0.0.40 as that's what we're going for. v40 is a big improvement

**Comment by Connoropolous** [comment]
@hector0513 could you take this one over?

Update the HDK to v0.0.40-alpha1?

**Comment by hector0513** [comment]
> @hector0513 could you take this one over?
> 
> Update the HDK to v0.0.40-alpha1?

yes

**Pull request closed without merging**
