### PR TITLE
use latest holonix

### PR DESCRIPTION
**Pull request by thedavidmeister**

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@Connoropolous 

> different computers don't seem to compile the DNA to the same hash

interesting :thinking: 

do we know why this is the case?

> Also, does it present a challenge if we update holochain binary, but not the HDK references

no it doesn't, i'm pushing for HDK and the holochain binaries to be separate repos upstream

once the holochain binary is compiled it doesn't matter what crates were used from our perspective

**Comment by Connoropolous** [comment]
> do we know why this is the case?

No, though I expect it has to do with dependencies... that's why I was committing the DNA file.

**Comment by thedavidmeister** [comment]
@Connoropolous ok yeah, makes sense if it is committed

how about now?

**Comment by Connoropolous** [comment]
@thedavidmeister another work item we could use your help on would be setting up a nix-shell CI for this repo, to run the tests. It wouldn't be worth it till after #48 is merged in, since we haven't had a working set of tests, but that will be valuable soon!

**Comment by thedavidmeister** [comment]
@Connoropolous i was going to ask about exactly that!

i noticed there is no CI running and that was bothering me a bit :P

i'm heading to georgia on thursday so i'm fairly busy this week but i'll try to knock up some CI tasks over the weekend :)

**Pull request merged**
