### PR TITLE
add circle

### PR DESCRIPTION
**Pull request by thedavidmeister**

### CODE REVIEW

**Comment by thedavidmeister** [comment]
@Connoropolous i added a real basic circle config file, can you setup the circle/github org so it runs?

**Comment by Connoropolous** [comment]
Yes

**Comment by Connoropolous** [comment]
Yes

**Comment by Connoropolous** [comment]
There, it's enable now :)

**Comment by Connoropolous** [comment]
@thedavidmeister the tests are passing locally, so would love to get CI cranking!

**Comment by thedavidmeister** [comment]
@Connoropolous when you say the tests are passing locally, do you mean `hc test`?

i can't see that passing myself :(

i tried bumping the versions of everything and it led to the test code being apparently out of date with the latest tryorama

if you know how to clean that up (see the latest build logs on circle for errors) then go for it, otherwise i'll look into it

**Comment by thedavidmeister** [comment]
@Connoropolous ok this is working, im using the old version of tryorama still

**Pull request merged**
